### ISSUE TITLE
Update failed with "Error: CTAP2_ERR_OPERATION_DENIED (0x27)"

### ISSUE THREAD

**Issue by emsix** [solokeys/solo-desktop#5]
Hi,

update under Windows 10 (1809 17763.864) failed with this error code.

![solo update failed](https://user-images.githubusercontent.com/58268056/69744378-5a5f5e00-1140-11ea-9726-1d0f97060a60.PNG)

Another question: What is meant by the abbreviation "WIP"?

**Comment by emsix** [comment]
Update: I got it running by using the provided commandline tools on another computer. The desktop application still shows this error code.

**Comment by Babene03** [comment]
@emsix why close it?

The function is not OK and solokeys must fix it.

**Comment by conorpp** [comment]
If you're still seeing this issue, can you see if it is still persisting with the `3.0.1.` firmware release?

**Comment by emsix** [comment]
> 
> 
> @emsix why close it?
> 
> The function is not OK and solokeys must fix it.

I am not sure if it's an not OK function. I had issues after I played to much with a tool calles "Zadiag" to instal different USB drivers. After I could restore the state from before, I was able to update severals Solokeys with "Solo Desktop".
